In [ ]:
import numpy as np
array =np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array.min()

1

In [ ]:
array.mean()

5.0

In [ ]:
array.median()


AttributeError: ignored

In [ ]:
array.argmin()

0

In [ ]:
array.argmax()

8

In [ ]:
sec1 =np.array(np.random.randit(10,20,[4,4]))
sec1

AttributeError: ignored

In [ ]:
sec1 =np.array(np.random.randint(10,20,[4,4]))
sec1

array([[16, 13, 12, 15],
       [12, 15, 11, 18],
       [17, 14, 11, 16],
       [19, 16, 11, 19]])

In [ ]:
sec2 =np.array(np.random.randint(10,20,[4,4]))
sec2    

array([[16, 16, 11, 16],
       [12, 11, 13, 14],
       [16, 16, 14, 16],
       [12, 14, 14, 18]])

In [ ]:
  np.vstack((sec1,sec2))

array([[16, 13, 12, 15],
       [12, 15, 11, 18],
       [17, 14, 11, 16],
       [19, 16, 11, 19],
       [16, 16, 11, 16],
       [12, 11, 13, 14],
       [16, 16, 14, 16],
       [12, 14, 14, 18]])

In [ ]:
  np.hstack((sec1,sec2))

array([[16, 13, 12, 15, 16, 16, 11, 16],
       [12, 15, 11, 18, 12, 11, 13, 14],
       [17, 14, 11, 16, 16, 16, 14, 16],
       [19, 16, 11, 19, 12, 14, 14, 18]])

In [ ]:
  sec1+sec2

array([[32, 29, 23, 31],
       [24, 26, 24, 32],
       [33, 30, 25, 32],
       [31, 30, 25, 37]])

In [ ]:
  sec1@sec2

array([[ 784,  801,  723,  900],
       [ 764,  785,  733,  902],
       [ 808,  826,  747,  932],
       [ 900,  922,  837, 1046]])

In [ ]:
  sec1.dot(sec2)

array([[ 784,  801,  723,  900],
       [ 764,  785,  733,  902],
       [ 808,  826,  747,  932],
       [ 900,  922,  837, 1046]])

In [ ]:
  sec1.transpose()

array([[16, 12, 17, 19],
       [13, 15, 14, 16],
       [12, 11, 11, 11],
       [15, 18, 16, 19]])

In [ ]:
  sec2.transpose()

array([[16, 12, 16, 12],
       [16, 11, 16, 14],
       [11, 13, 14, 14],
       [16, 14, 16, 18]])

In [ ]:
  sec2.trace()

59

In [ ]:
sec1.trace()

61

In [ ]:
np.abs(-100.25)

100.25

In [ ]:
np.all(sec1>0)

True

In [ ]:
np.all(sec1>56)

False

In [ ]:
np.all(sec2>0)

True

In [ ]:
np.any(sec1<0)

False

In [ ]:
np.any(sec1>0)

True

In [ ]:
  np.round(12.36)

12.0

In [ ]:
  np.round(9494.74833)

9495.0

In [ ]:
np.floor(34.99)

34.0